### ISSUE TITLE
includeTooltip: false does not hide tooltip

### ISSUE THREAD

**Issue by puinenveturi** [rcsb/rcsb-saguaro#19]
I have configured `includeTooltip: false` settings in both RcsbFvRowConfigInterface and RcsbFvBoardConfigInterface, but the tooltip (zoom in/out, step left/right) still appears. Have I misunderstood this setting or does the viewer ignore this option?

![tooltip](https://user-images.githubusercontent.com/2670175/120174640-98da4b00-c205-11eb-87f2-05d608bb1343.png)

**Comment by bioinsilico** [comment]
Thank you for your interest in rcsb-saguaro. includeTooltip can be used to display/hide the tooltip that appears when hovering elements. I have realized that this configuration was not working at all (now it should be fixed). In addition, I have added a new option -disableMenu- to the board configuration interface (RcsbFvBoardConfigInterface) to hide the UI menu. Please, can you update to rcsb-saguaro 1.8.0 and check if the new changes work for you ?

**Comment by puinenveturi** [comment]
`disableMenu` did work like a charm, thank you for the quick response and for updating the CDN URL in the readme!
