### ISSUE TITLE
Broken doc links in README

### ISSUE THREAD

**Issue by gabrielctn** [rcsb/rcsb-saguaro#24]
Hi !
It looks like the links provided in the README are not valid.
![image](https://user-images.githubusercontent.com/25644865/157887896-7991e7b5-f570-46b8-b2da-f634443cbd27.png)

Here is what I get when clicking on
https://rcsb.github.io/rcsb-saguaro/classes/rcsbfv.html

![image](https://user-images.githubusercontent.com/25644865/157887531-0438316f-5f89-414e-acf2-09141ccf5200.png)

I believe you need to setup an index.html file on the root directory of the repo.

Thanks for your work !

**Comment by gabrielctn** [comment]
Yeah, so actually it is only a matter of lower/uppercase, the links to the html files must absolutely match the actual file in the repo, e.g. https://rcsb.github.io/rcsb-saguaro/classes/RcsbFv.html instead of https://rcsb.github.io/rcsb-saguaro/classes/rcsbfv.html

**Comment by bioinsilico** [comment]
@gabrielctn Thank you for reporting this. The problem arose after updating the typedoc library. Now the links should work in github pages. For the NPM repo I will wait to publish a new version of the package.

**Comment by gabrielctn** [comment]
Great !! Thank you !
