### ISSUE TITLE
Customizing tooltips?

### ISSUE THREAD

**Issue by duyendotnguyen** [rcsb/rcsb-saguaro#28]
Is there a way to customize the information that appears when someone hovers over an annotation within any of the tracks? It looks like the example on the [github page](https://rcsb.github.io/rcsb-saguaro/) displays additional information (e.g. the source, the secondary structure type, etc.), and see there are a lot of optional attributes that can be included in`RcsbFvTrackDataElementInterface`, but don't know how to actually include it and get it to appear. I've looked through the CodePens, and none of them seem to have examples of how to do this.

**Comment by bioinsilico** [comment]
Hi @duyentnguyen! Sorry about my late response. Currently, it is not possible to customize from the outside. I need to refactor the popups method with a better design. The file https://github.com/rcsb/rcsb-saguaro/blob/master/src/RcsbBoard/RcsbTooltip/RcsbTooltipManager.ts contains the logic of how popups are generated from a `RcsbFvTrackDataElementInterface`. The popups can be configured for individual elements using these fields

`{
                name: "Name",
                provenanceName: "ProvenanceName",
                provenanceColor: "green",
                begin: 50,
                end: 80,
                source: "Source",
                sourceId: "SourceId",
                oriBegin: 70,
                oriEnd: 100
}`

Please, let me know if you have any question.

**Comment by duyendotnguyen** [comment]
Thanks so much for your response! For my use case, I think it's enough (for now) that I'm able to add extra information using the fields you listed above. Thank you for providing this as a resource!! Will close the issue out, too.
