### ISSUE TITLE
"trackVisibility" not working in 2.5.9

### ISSUE THREAD

**Issue by duyendotnguyen** [rcsb/rcsb-saguaro#35]
hi! I was using version `2.2.17` of the package, and was able to configure initial rows visibility using `trackVisibility: false` or `trackVisibility: true`. I thought it might be a good idea to update my package to `2.5.9` (which seems to be the latest one), but the `trackVisibility` initial config no longer seems to have any effect.

Not sure if this is a bug, or something I'm doing wrong on my end?

Example row config I'm using is:
```
{
    displayDomain: [0, 255],
    displayType: "area",
    rowTitle: "Molar mass (g/mol)",
    trackColor: "#F9F9F9",
    trackData: [...],
    trackHeight: 45,
    trackId: "Molar mass (g/mol)",
    trackVisibility: false
}

**Comment by bioinsilico** [comment]
Thank you so much, @duyentnguyen, for reporting this bug. Could you please update to v2.5.10 and report back?

**Comment by duyendotnguyen** [comment]
just gave it a try, and it seems to be working again! thanks so much for looking into this so quickly!
