### ISSUE TITLE
If trackVisibility is false for some tracks on board creation, then the "Loading" indicator will be shown on the right side

### ISSUE THREAD

**Issue by jordansafer** [rcsb/rcsb-saguaro#36]
For our usecase, we have many tracks, and most are disabled by default. The user then has the option to add/enable tracks that they'd like to see. Right now, when the board loads, the loading message remains, saying for example "LOADING 22%". The message remains until the user makes 100% of tracks visible.

I've checked through the RCSBFv code, and found that this makes sense currently, because when a row is set to be rendered it triggers a ROW_READY event. After 100% of rows trigger the ROW_READY event, the Progress component reaches progress complete, and the "LOADING" message becomes hidden. I think, to address this, the progress complete would need to be separated from the ROW_READY event, possibly by creating 2 separate events, for example ROW_READY_FOR_RENDER and ROW_LOADED. The simplest workarounds for now (for users :) ) are either to make all tracks visible to start, hide tracks by removing them from board data, or to override CSS to hide the loading bar.

**Comment by jordansafer** [comment]
The issue is visible right now on https://g2p.broadinstitute.org/, although I'm putting out a fix on our end soon :)
<img width="1349" alt="Screenshot 2023-05-04 at 4 37 07 PM" src="https://user-images.githubusercontent.com/8800717/236323749-7e9be0a8-881c-4192-b552-127ba42cf102.png">

**Comment by bioinsilico** [comment]
Thank you so much for reporting this bug, @jordansafer. Please could you update to the last version (v2.5.11) and report back?

**Comment by jordansafer** [comment]
Hi yes! It is working- Thank you!
