### ISSUE TITLE
Partially visible tracks don't change when zooming

### ISSUE THREAD

**Issue by kimrutherford** [rcsb/rcsb-saguaro#37]
Hi.  Thanks for creating a great library.  We're working on using it to [display protein features](https://github.com/pombase/website/issues/2053) on the [PomBase](https://www.pombase.org/) gene pages.

We've noticed that if a track is only partially visible it doesn't change when zooming.

As an example from the [3NR1 page](https://www.rcsb.org/sequence/3NR1), here's what it looks like when showing the full sequence with the DISORDER track slightly overlapping the bottom of the browser window:

![image](https://github.com/rcsb/rcsb-saguaro/assets/90474/adc839dd-db82-495e-8101-762e682b0833)

When I zoom in the DISORDER track doesn't change:

![image](https://github.com/rcsb/rcsb-saguaro/assets/90474/9b5d298f-e11e-481d-81f2-d847d991ff3f)

The DISORDER track updates as soon as I scroll it fully into view:

![image](https://github.com/rcsb/rcsb-saguaro/assets/90474/9a37bcb3-7c32-429d-8078-c01bc20b3357)

This happens on Chrome and Firefox.

**Comment by bioinsilico** [comment]
Thank you, @kimrutherford, for reporting this bug. In short, the problem was due to the configuration of the `IntersectionObserver` that the zoom was not applied until all element pixels fitted inside the display port. We changed to condition to any pixel. Now RCSB.or should behave as expected.

**Comment by kimrutherford** [comment]
Thanks very much!  That has fixed the problem for us.
