### ISSUE TITLE
Changing font size

### ISSUE THREAD

**Issue by seantycho** [rcsb/rcsb-saguaro#39]
Is there a way to configure/change the font size of sequences? My quick look though led me to believe it's somewhat hardcoded but I just wanted to make sure. Size 10 font is a bit small for some peoples eyes and it would be nice to be able to pass in a font-size as part of the config. Cheers!

**Comment by bioinsilico** [comment]
Thank you for your question, @seantycho. You are right. Currently, font size is hardcoded. Let me think about adding a more general configuration style for the tracks.

**Comment by seantycho** [comment]
Great, thanks for the response! Happy to close this issue.
