### ISSUE TITLE
Highlighting particular position

### ISSUE THREAD

**Issue by skrhakv** [rcsb/rcsb-saguaro#40]
Hello,

I am working on interconnecting your tool with the [Molstar Viewer](https://github.com/molstar/molstar): when a user hovers over the residues in Mol*, I would like to highlight the particular residue in the RCSB Saguaro Viewer. Is there a way to highlight a particular position in the viewer?

Thanks for your help in advance!

Vit

**Comment by bioinsilico** [comment]
Thank you, @skrhakv, for your question. I would suggest checking our project https://github.com/rcsb/rcsb-saguaro-3d. It is the integration of molstar and rcsb-saguaro.

If, for some reason, you want to do the integration yourself, you should use the method `addSelection` https://rcsb.github.io/rcsb-saguaro/classes/RcsbFv.html#addSelection

**Comment by skrhakv** [comment]
Thank you @bioinsilico for the tip and for your advice! The `addSelection` function worked like a charm.

Unfortunately, I did not know that the project integrating Molstar and RCSB-Saguaro exists. Therefore I will definitely put it into my TODO list for the future, as I try to keep my codebase clean.
